services:
  frontend:
    image: vuejs/ci:latest
    container_name: vuejs
    depends_on:
      - backend
      - database
    restart: always
    env_file: .env
    ports:
      - "8080:8080"

  backend:
    # image: nestjs/cli:latest
    build: src/backend
    container_name: nestjs
    depends_on:
      - database
    restart: always
    env_file: .env
    ports:
      - "3000:3000"
    networks:
      - back-tier
    volumes:
      - ./src/backend/:/home/data
    # stdin_open: true
    # tty: true

  database:
    image: postgres:latest
    container_name: postgres
    # depends_on:
    restart: always
    env_file: .env
    volumes:
      - db-data:/etc/data
    ports:
      - "5432-5433:5432-5433"
    networks:
      - back-tier


volumes:
  db-data: {}

networks:
  back-tier: {}



# expose Ports