services:
  frontend:
    container_name: frontend

    build:
      context: ./src/frontend/
    # image: vuejs/ci:latest
    # depends_on:
    #   - backend
    #   - database
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./src/frontend/src/:/app/src/
    # env_file: .env


  backend:
    build: src/backend
    container_name: nestjs
    depends_on:
      - database
    restart: always
    ports:
      - "3000:3000"
    networks:
      - back-tier
    volumes:
      - ./src/backend/src:/home/data/src
    # env_file: .env
    # image: nestjs/cli:latest
    # stdin_open: true
    # tty: true

  database:
    build: src/database
    container_name: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432-5433:5432-5433"
    networks:
      - back-tier
    env_file: ./src/backend/.env

    # env_file: .env
    # depends_on:






volumes:
  db-data:
    name: "db-data"

networks:
  back-tier: {}



# expose Ports
