FROM node:18

WORKDIR /home/data


# RUN apt-get update -y && apt upgrade -y
# RUN apt-get install -y curl bash
# RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash -E
# RUN apt-get install -y nodejs
# RUN apt-get install -y npm
RUN  npm install -g @nestjs/cli



# RUN pwd

# RUN ls
# RUN apt update

CMD [ "npm", "run", "start"]